### ISSUE TITLE
Desired outputs

### ISSUE THREAD

**Issue by MikeLydeamore** [numbats/achievement-scraper#12]
As per George:

* All articles per year, including their links
* Summarised articles by author, journals, and rankings
* For each staff member: h-index, total citations, top 10 cited outputs
* Package name, number of downloads, date of last update

We can aim to have two dataframes: One for research outputs and one for software.

**Research frame**

* title
* DOI
* authors
* publication_date
* journal_name

**Software frame**

* software_name
* authors
* num_downloads
* last_update_date
* original_publish_date (if available)

**Comment by Sherrydaboo** [comment]
Hi Michael, 

As from my understanding, the main function we will need is one that takes in a Scholar ID, and an Orcid ID, and returns a list of publications. 

1. Does that mean the **return publications** 
- need All articles per year, including their links
- Summarised articles by author, journals, and rankings
- For each staff member: h-index, total citations, top 10 cited outputs
- Package name, number of downloads, date of last update? 

2. As for the two dataframes: One for research outputs and one for software, are we supposed to create two more files for summarize_research.R and summarize_software.R within the R folder? 

Thanks,
Sherry

**Comment by MikeLydeamore** [comment]
1. No, I think we can build these outputs from the main function that you're describing.
2. These two dataframes would be the outputs from the main function(s). So, the function that takes in a scholar ID and an Orcid ID would return a dataframe with those 5 columns.
