### ISSUE TITLE
Issue with Extracting DOI from ORCID Works Data

### ISSUE THREAD

**Issue by parnikakhattri** [numbats/achievement-scraper#16]
Hi Michael,

I am encountering an error when trying to extract DOI information as it is giving me other elements including eid, issn.

![Screen Shot 2024-08-30 at 1 10 33 pm](https://github.com/user-attachments/assets/d4138379-5966-4e21-9fed-ce61c582dafd)

Can you suggest me a function to get only doi out of this data?

**Comment by MikeLydeamore** [comment]
This was hard to do! I've pushed some code that maps over the list (which is what is in your screenshot) and pulls out just the DOI. Haven't tested it extensively, but see how it goes.

**Comment by parnikakhattri** [comment]
I'll give it a try and see how it goes. Thanks for your help Michael!
