### ISSUE TITLE
 Clarification on Combiner Function for Software Data Frame

### ISSUE THREAD

**Issue by parnikakhattri** [numbats/achievement-scraper#17]
Hi Michael,

We've implemented the combiner function for the research dataframe. However, I'm a bit confused about how to proceed with the software data frame(CRAN DOWNLOADS). Should the combiner function for software be added within the existing combiner.R file, integrated into the get_publications(orcid_id, scholar_id) function, or should we create a new separate function for it?

Thank you for your guidance.

Best regards,
Parnika

**Comment by MikeLydeamore** [comment]
I think this has been fixed now with the current structure. Please re-open the issue if not.
