### ISSUE TITLE
Update function to incorporate invalid ORCID IDs

### ISSUE THREAD

**Issue by parnikakhattri** [numbats/achievement-scraper#18]
get_publications_from_orcid returns empty data frame for invalid ORCID IDs but it  is throwing an error.
![Screen Shot 2024-09-12 at 12 09 06 pm](https://github.com/user-attachments/assets/9688cdd6-3e5f-4841-9acc-c783483694f0)
Also, do we need to do the same procedure for invalid id fromnget_publications_from_scholar?

**Comment by MikeLydeamore** [comment]
I've pushed the fix we started in the meeting today for the ORCID IDs. You'll still need to fix the test (which should now expect_error).

What error is thrown if you give an invalid Scholar ID?
