### ISSUE TITLE
Author not traceable in Orcid Publications

### ISSUE THREAD

**Issue by parnikakhattri** [numbats/achievement-scraper#19]
I just picked a random orcid_id get_publications_from_orcid("0000-0001-9379-0010") but running this code gives me an error?
![Screen Shot 2024-09-12 at 12 12 47 pm](https://github.com/user-attachments/assets/ccfd6b56-28ce-4eeb-b984-e7fbfb5d2b2a)

**Comment by MikeLydeamore** [comment]
This was harder to fix than I thought. I have added a new function in `util.R` that appends a column onto a dataframe if it doesn't exist, and just called that 6 times, and it seems to have solved the problem for now.

I've also added a test for this ORCID ID to ensure all the columns are there.
