### ISSUE TITLE
Query Regarding DOI Retrieval for Publications from Google Scholar

### ISSUE THREAD

**Issue by Sherrydaboo** [numbats/achievement-scraper#20]
Hi Rob and Michael,

While working on retrieving publication data from Google Scholar, I encountered an issue regarding the DOI information. The code is currently returning NA for DOIs, and after some research, I discovered that Google Scholar does not seem to share DOI information directly.

Several sources, including https://webapps.stackexchange.com/questions/93339/obtaining-the-doi-in-google-scholar and https://libguides.com.edu/c.php?g=649172&p=4554037, confirm that Google Scholar doesn't include DOIs in its results. To get the DOI, it seems necessary to manually click through to the article page and retrieve it from the publisher's site.

I wanted to ask if there’s any alternative way you would recommend for retrieving DOIs, or if there's a method I might have overlooked. Any guidance on this issue would be greatly appreciated.

Thank you for your time!

**Comment by MikeLydeamore** [comment]
Yes Google Scholar doesn't return DOIs. We can just leave them as NA. They will get picked up by ORCID sometimes, and otherwise they can just stay blank.
