### ISSUE TITLE
Incorrect Top Authors by Publications Visualization

### ISSUE THREAD

**Issue by Sherrydaboo** [numbats/achievement-scraper#22]
Hi Michael and Rob, we have tried removing the filter(authors %in% author_names) from the code, but in the vignettes, we are still encountering three issues:

1. The top author is returning NA, which is unexpected.
2. The author "Yu Bai" appears in the top 5, which we believe is still incorrect. 
3. Rob's number of publications still returning the same.

We believe that there may be duplicate names in the data caused by multiple individuals with the same name (e.g., different researchers named "Yu Bai", we searched it up, there's actually another person called Yu Bai). Additionally, the NA value might be caused by missing or improperly formatted author metadata in the dataset. 

How can we handle the issue to ensure the authors are correctly distinguished and how can we ensure that authors like Rob, who are known to have a high number of publications, are correctly represented?

**Comment by robjhyndman** [comment]
Have a look at what is being returned by `get_all_publications(orcid_gsid)`. That should show you why the author filter is not working.

Then look at those lines with missing authors. Figure out why the authors are missing from those papers.

The orcid you have in the data set for Yu Bai is for the wrong person. I couldn't find the correct Yu Bai on the orcid website. So set his orcid ID to NA.

**Comment by parnikakhattri** [comment]
![Screen Shot 2024-10-07 at 2 49 10 pm](https://github.com/user-attachments/assets/78ce087d-ea5a-4c68-821a-d1708e90844d)

Hi Michael and Rob, Can you please check that if the plot is giving the correct result?

**Comment by robjhyndman** [comment]
You can compare the numbers of publications shown in the graph with the numbers of publications shown in each person's orcid profile. For example, mine is at https://orcid.org/0000-0002-2140-5352 and shows 232 publications. George Athanasopoulos is at https://orcid.org/0000-0002-5389-2802 and shows 95 publications. There may be reasons for these numbers to be different from what you are showing in the graph, but you should investigate why.

**Comment by parnikakhattri** [comment]
Thank you for pointing that out. I will investigate it.
