### ISSUE TITLE
Create list of EBS ORCID ids

### ISSUE THREAD

**Issue by robjhyndman** [numbats/achievement-scraper#4]
This file contains many Monash people (and plenty of others). It's a starting point for making a list of EBS orcid ids.

[ACEMS2021.csv](https://github.com/user-attachments/files/16384403/ACEMS2021.csv)

**Comment by parnikakhattri** [comment]
Do we need the EBS ORCID IDs in the form of full URLs, or is just the 16-digit code sufficient?

**Comment by robjhyndman** [comment]
Just the 16-digit code is better and simpler. We can always construct the URLs from the code if we need it.

**Comment by parnikakhattri** [comment]
Awesome, thanks.

**Comment by parnikakhattri** [comment]
I have compiled a list of authors along with their ORCID IDs and have pushed the updated file to my branch named 'parnika'. Could you please review it and let me know if there are any changes required or if it meets the project’s standards?

**Comment by robjhyndman** [comment]
A good start. Next remove the people who are not staff members at EBS, and add anyone from EBS who is missing. You can find the EBS staff list at https://www.monash.edu/business/ebs/our-people/staff-directory

**Comment by parnikakhattri** [comment]
Thanks for the update, Rob. I have updated the ORCID IDs of EBS staff. However, I noticed that we have the ORCID IDs for only two people from EBS Department. Is there any other place I can find the missing ORCID IDs for these individuals?

**Comment by robjhyndman** [comment]
Search the orcid website: https://orcid.org/
Try searching for a name followed by "Monash". e.g., "Jack Jewson Monash" finds Jack.

**Comment by parnikakhattri** [comment]
Hi Rob,

Thank you for the clarification. I have updated the list of EBS ORCID IDs in the main branch. However, I have a few questions:

1. There are 24 Monash Professors who do not have ORCID IDs. Is it acceptable to remove these entries with NA values?
2. Should the names be converted to lowercase?
3. Currently, the names are formatted as per the Monash staff directory. I noticed that on the ORCID ID website, some professors have slightly different names. Should we adhere to the format from the staff directory or the ORCID ID website?

**Comment by robjhyndman** [comment]
1. I think you need to work harder to find them. I looked for the first three on your list with NA values, and found two of them without much trouble: [Jiti Gao](https://orcid.org/0000-0002-4261-0021) and [Damjan Vukcevic](https://orcid.org/0000-0001-7780-9586). I'd be surprised if there were many without IDs.
2. I suggest we use Firstname Lastname as the standard for names.
3. Yes, I think we should use what is on the Monash EBS staff directory website.

One other thing: In R packages, the `data` folder is for `.rda` files that form part of the package. You should put these csv files in a `data-raw` folder, and then we can add them as `.rda` files using the `usethis::use_data()` function. See https://r-pkgs.org/data.html for details about adding data to packages.

**Comment by parnikakhattri** [comment]
Thanks for the update, Rob. I have made the changes as suggested.

**Comment by robjhyndman** [comment]
Didier: https://orcid.org/0000-0003-4398-4321
