### ISSUE TITLE
Create list of EBS Google scholar IDs

### ISSUE THREAD

**Issue by robjhyndman** [numbats/achievement-scraper#5]
This is a starting point
[database.csv](https://github.com/user-attachments/files/16384415/database.csv)

**Comment by Sherrydaboo** [comment]
Hi Rob,

I have implemented the updates and included the current list of EBS authors in the script. Could you please review and let me know if I'm on the right track?

Many thanks,
Sherry

**Comment by robjhyndman** [comment]
Good start. We don't need to keep the URLs as we can construct them from the IDs. Also, please remove people who are no longer in the department, and add people who are not on the list. The current EBS staff list is at https://www.monash.edu/business/ebs/our-people/staff-directory

**Comment by Sherrydaboo** [comment]
Hi Rob,

I have manually entered the current EBS staff details from the staff web into an Excel file and saved it as a CSV file called EBS_staff_web.csv. I have also updated the data using this file in the R code, resulting in an updated file called gsid_updated.csv. Both files contain the same data, with one entered manually for accuracy.

I have included only the Name and GSuserID in the updated file. Many of the staff members do not have a GSuserID in the updated file. Could you please confirm if this approach is correct?

**Comment by robjhyndman** [comment]
Yes, we just need Name and GS user ID in the file. But you now have three files with that information, and we just need one. Also, you need to try to find the GS IDs for those who currently don't have one. Not all will have one, but many will.

**Comment by robjhyndman** [comment]
You really need to try harder. It was easy to find these ones:
https://scholar.google.com.au/citations?hl=en&user=Y2_fkj8AAAAJ
https://scholar.google.com.au/citations?hl=en&user=n78g02EAAAAJ
https://scholar.google.com.au/citations?hl=en&user=XBlL5AQAAAAJ
https://scholar.google.com.au/citations?hl=en&user=iAp7jfQAAAAJ
https://scholar.google.com.au/citations?hl=en&user=I8v-44UAAAAJ
https://scholar.google.com.au/citations?hl=en&user=WfbnEuAAAAAJ
https://scholar.google.com.au/citations?hl=en&user=BVke6rMAAAAJ
https://scholar.google.com.au/citations?hl=en&user=KJfOVqoAAAAJ
https://scholar.google.com.au/citations?hl=en&user=dIaNw8MAAAAJ
https://scholar.google.com.au/citations?hl=en&user=cODjyskAAAAJ

**Comment by robjhyndman** [comment]
https://scholar.google.com.au/citations?hl=en&user=nRhrZnIAAAAJ

**Comment by Sherrydaboo** [comment]
Thank you for the feedback and the additional Google Scholar IDs. I appreciate your guidance and will use these to proceed with the task.
