### ISSUE TITLE
Package functions 

### ISSUE THREAD

**Issue by Sherrydaboo** [numbats/achievement-scraper#7]
Functions that across the department can run, how users will be using the functions for. 

- Search Function (Input - Orcid ID, Scholarly ID, Name (First Name + Last Name), Output - Publications)

**Comment by parnikakhattri** [comment]
What is the ideal number of functions the package should contain/ or we aiming for?

**Comment by Sherrydaboo** [comment]
I am thinking to do about 3 key functions which consist of
**1. Search by ORCID ID
2. Search by Google Scholar ID
3. Search by Name**

And other function ideas could be :

- Search by keywords

- Filter publications by year- This function allows users to filter the retrieved publications by a specific year or range of years.

- Summarise publications- This function provides a summary of the publications, such as the number of publications per year, most common journals, etc.

Please let me know if you have any other suggestions or if there are specific requirements we should consider. Thanks.

**Comment by MikeLydeamore** [comment]
The main function we will need is one that takes in a Scholar ID, and an Orcid ID, and returns a list of publications. The skeleton would be something like:

```{r}
get_publications <- function(orcid_id, scholar_id) {
# Scrape Google Scholar
# Scrape ORCID

# Combine into one tibble, de-deduplicate and return
}
```

Having the list of IDs is convenient and useful, but isn't the main functionality we will need to implement.

It's also a good idea to break up the above function into two other functions. Something like `get_publications_from_scholar` and `get_publications_from_orcid`.

**Comment by Sherrydaboo** [comment]
Hi Mike, can we please get the package name for the use of scraping the Google Scholar? As mentioned in our last meeting.

**Comment by MikeLydeamore** [comment]
https://github.com/jkeirstead/scholar, or you can use the CRAN version as well
