### ISSUE TITLE
Add code to data-raw that creates the `orcid_gsid.rds` file

### ISSUE THREAD

**Issue by MikeLydeamore** [numbats/achievement-scraper#9]
It is best practice to include the code that converts the CSV to the `rds` file. This code should go inside `data-raw`. See [here](https://github.com/hadley/babynames/blob/master/data-raw/lifetables.R) for a good example.

Make sure the file ends with a call to `usethis::use_data(object_name)`. That will make sure everything is exported as we expect.

**Comment by parnikakhattri** [comment]
Sure, I understand. Thanks, Micheal.
